### ISSUE TITLE
httpd 500 from lucene while using Python hook script. CouchDB 1.5

### ISSUE THREAD

**Issue by rakeshag** [rnewson/couchdb-lucene#194]
I am getting Error 500. Please see log from CouchDb. Also included definition of the view.

Also tried the Proxy Handler configuration before Python configuration but had got the same error.

I do not see any activity in the lucene server logs. Hence the call fails on the CouchDB side. The Couch DB did start the python hook script from tools.

What could I be missing in the configuration?

Thank you

-Rakesh

---------------------
CouchDB logs
-----------------------
[Thu, 17 Apr 2014 23:50:27 GMT] [debug] [<0.3039.0>] 'GET' /locations/_fti/_design/foo/by_country?q=China {1,
                                                                           1} from "127.0.0.1"
Headers: [{'Accept',"*/*"},
          {'Host',"localhost:5984"},
          {'User-Agent',"curl/7.30.0"}]
[Thu, 17 Apr 2014 23:50:27 GMT] [debug] [<0.3039.0>] OAuth Params: [{"q","China"}]
[Thu, 17 Apr 2014 23:50:27 GMT] [debug] [<0.288.0>] OS Process #Port<0.3405> Input  :: {"info":{"db_name":"locations","doc_count":2226,"doc_del_count":2,"update_seq":2230,"purge_seq":0,"compact_running":false,"disk_size":8061041,"data_size":830154,"instance_start_time":"1397775899591366","disk_format_version":6,"committed_update_seq":2230},"id":null,"uuid":"d09765f3c0e57a91b74607bfc6003d17","method":"GET","requested_path":["locations","_fti","_design","foo","by_country?q=China"],"path":["locations","_fti","_design","foo","by_country"],"raw_path":"/locations/_fti/_design/foo/by_country?q=China","query":{"q":"China"},"headers":{"Accept":"*/*","Host":"localhost:5984","User-Agent":"curl/7.30.0"},"body":"undefined","peer":"127.0.0.1","form":{},"cookie":{},"userCtx":{"db":"locations","name":null,"roles":["_admin"]},"secObj":{}}
[Thu, 17 Apr 2014 23:50:27 GMT] [debug] [<0.288.0>] OS Process #Port<0.3405> Output :: {"body": "Traceback (most recent call last):\n  File \"/usr/local/opt/couchdb-lucene/tools/couchdb-external-hook.py\", line 40, in main\n    resp = respond(res, req, opts.key)\n  File \"/usr/local/opt/couchdb-lucene/tools/couchdb-external-hook.py\", line 81, in respond\n    res.request(method, path, headers=req_headers)\n  File \"/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/httplib.py\", line 973, in request\n    self._send_request(method, url, body, headers)\n  File \"/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/httplib.py\", line 1007, in _send_request\n    self.endheaders(body)\n  File \"/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/httplib.py\", line 969, in endheaders\n    self._send_output(message_body)\n  File \"/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/httplib.py\", line 829, in _send_output\n    self.send(msg)\n  File \"/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/httplib.py\", line 791, in send\n    self.connect()\n  File \"/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/httplib.py\", line 772, in connect\n    self.timeout, self.source_address)\n  File \"/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/socket.py\", line 571, in create_connection\n    raise err\nerror: [Errno 61] Connection refused\n", "headers": {"Content-Type": "text/plain"}, "code": 500}
[Thu, 17 Apr 2014 23:50:27 GMT] [info] [<0.3039.0>] 127.0.0.1 - - GET /locations/_fti/_design/foo/by_country?q=China 500
[Thu, 17 Apr 2014 23:50:27 GMT] [error] [<0.3039.0>] httpd 500 error response:
 Traceback (most recent call last):
  File "/usr/local/opt/couchdb-lucene/tools/couchdb-external-hook.py", line 40, in main
    resp = respond(res, req, opts.key)
  File "/usr/local/opt/couchdb-lucene/tools/couchdb-external-hook.py", line 81, in respond
    res.request(method, path, headers=req_headers)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/httplib.py", line 973, in request
    self._send_request(method, url, body, headers)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/httplib.py", line 1007, in _send_request
    self.endheaders(body)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/httplib.py", line 969, in endheaders
    self._send_output(message_body)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/httplib.py", line 829, in _send_output
    self.send(msg)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/httplib.py", line 791, in send
    self.connect()
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/httplib.py", line 772, in connect
    self.timeout, self.source_address)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/socket.py", line 571, in create_connection
    raise err
error: [Errno 61] Connection refused

DESIGN DOC for the View:
------------------------------------
{
   "_id": "_design/foo",
   "_rev": "1-7322a931b68db4a99bee4bc8b3d40194",
   "fulltext": {
       "by_country": {
           "index": "function(doc) { var ret=new Document(); ret.add(doc.country); return ret }"
       },
       "by_state": {
           "index": "function(doc) { var ret=new Document(); ret.add(doc.state); return ret }"
       },
       "by_city": {
           "index": "function(doc) { var ret=new Document(); ret.add(doc.city); return ret }"
       },
       "by_name": {
           "index": "function(doc) { var ret=new Document(); ret.add(doc.name); return ret }"
       }
   }
}

**Comment by larsimmisch** [comment]
I have a similar problem. `couchdb-lucene` is running, appears to be working, but couchdb returns an internal server error (I assume due to a timeout, but that is speculation).

`curl localhost:5985` and`curl 127.0.0.1:5985` return:
`{"couchdb-lucene":"Welcome","version":"1.1.0-SNAPSHOT"}`

But couchdb logs:

`[Mon, 28 Sep 2015 13:02:15 GMT] [info] [<0.968.489>] 10.222.227.132 - - GET /_fti/local/recipes/_design/couchpotato/by-content?q=%22hefe%22&include_docs=true 500`

Running `couchdb-lucene` with loglevel debug produces:
```
2015-09-28 13:01:49,666 INFO [Config] Index output goes to: /usr/local/couchdb-lucene-1.1.0-SNAPSHOT/indexes
2015-09-28 13:01:49,955 INFO [Main] Accepting connections with SelectChannelConnector@localhost:5985
2015-09-28 13:02:04,172 DEBUG [recipes] NIOFSDirectory@/usr/local/couchdb-lucene-1.1.0-SNAPSHOT/indexes/967d3b56-f997-43bb-b283-36275aa279fa/6n7n7idfk8tpx4lj9u2fo7ell lockFactory=org.apache.lucene.store.SingleInstanceLockFactory@845f60 bumped since to 306
2015-09-28 13:02:05,280 DEBUG [recipes] paths: {_design/couchpotato/by-content=View[name=_design/couchpotato/by-content, digest=6n7n7idfk8tpx4lj9u2fo7ell]}
2015-09-28 13:02:05,293 INFO [recipes] Indexing from update_seq 306
```

**Comment by rnewson** [comment]
Do you have the response body of the 500? couchdb should have logged it;

```
    if Code >= 500 ->
        ?LOG_ERROR("httpd ~p error response:~n ~s", [Code, Body]);
```

**Comment by larsimmisch** [comment]
No, I don't; there doesn't seem to be one.

All I have is:

    [Wed, 30 Sep 2015 12:11:26 GMT] [info] [<0.930.46>] 10.222.227.132 - - GET /_fti/local/recipes/_design/couchpotato/by-content?q=%22hefe%22&include_docs=true 500

If I stop couchdb-lucene, I do get an error response:

    [Wed, 30 Sep 2015 12:10:08 GMT] [error] [<0.1240.46>] httpd 500 error response:
 {"error":"error","reason":"{conn_failed,{error,econnrefused}}"}

So it looks as if couchdb-lucene is not sending a response.

Is there an easy way to test this directly? i.e. a POST to couchdb-lucene without going through couchdb?

**Comment by rnewson** [comment]
that *is* the response body :) Did you change ports of couchdb or couchdb-lucene? Are they on the same machine?

**Comment by larsimmisch** [comment]
No and yes.

Are you sure there is a response body in the first log snippet? In this one?

   [Wed, 30 Sep 2015 12:11:26 GMT] [info] [<0.930.46>] 10.222.227.132 - - GET /_fti/local/recipes/_design/couchpotato/by-content?q=%22hefe%22&include_docs=true 500

Because the error response (`econnrefused`) is not my problem. That was from a run where I had deliberately shut down couchdb-lucene to see if I could get an error body. I have included it to highlight the differences, but I realize it may have been more confusing than helpful, sorry.

My problem seems to be that I get no response from couchdb-lucene in the normal case. The `GET` with a 500 response is all I see in the normal case.

**Comment by rnewson** [comment]
the GET you did to 5985 confirms that c-l is responding. can you test localhost:5984 and 127.0.0.1:5984 as well?

**Comment by larsimmisch** [comment]
Yup, couchdb is reachable on localhost and 127.0.0.1 on that machine:

    {"couchdb":"Welcome","uuid":"e3f8be32cda3a875a64df54c07439779","version":"1.6.1","vendor":{"name":"The Apache Software Foundation","version":"1.6.1"}}

**Comment by rnewson** [comment]
hm, tricky, the logs on both sides are quite unhelpful. One more thing to try is to modify couchdb-lucene.ini and supply a user:pass for an admin user, perhaps this is a permissions thing (very poorly reported). That is;

[local]
url = http://user:pass@localhost:5984/

**Comment by larsimmisch** [comment]
Ok, I think I found it. Deep down it was a simple permission issue, and after fixing the permission issue, c-l is now working as expected.

But the timing of that stack backtrace was weird. I did not see it when observing the logs while starting queries. I think this one was logged when I restarted c-l. Have a look at the times in the log messages yourself.

(To me this looks like a deadlock in an error case)

In any case, thank you for your work and your very fast responses!

```
2015-09-30 12:11:16,029 INFO [recipes] Indexing from update_seq 306
2015-09-30 18:34:10,574 WARN [recipes] Exiting due to exception.
java.io.FileNotFoundException: /usr/local/couchdb-lucene-1.1.0-SNAPSHOT/indexes/967d3b56-f997-43bb-b283-36275aa279fa/6n7n7idfk8tpx4lj9u2fo7ell/_1.fdx (Permission denied)
	at java.io.FileOutputStream.open0(Native Method)
	at java.io.FileOutputStream.open(FileOutputStream.java:270)
	at java.io.FileOutputStream.<init>(FileOutputStream.java:213)
	at java.io.FileOutputStream.<init>(FileOutputStream.java:162)
	at org.apache.lucene.store.FSDirectory$FSIndexOutput.<init>(FSDirectory.java:389)
	at org.apache.lucene.store.FSDirectory.createOutput(FSDirectory.java:282)
	at org.apache.lucene.store.TrackingDirectoryWrapper.createOutput(TrackingDirectoryWrapper.java:44)
	at org.apache.lucene.codecs.compressing.CompressingStoredFieldsWriter.<init>(CompressingStoredFieldsWriter.java:110)
	at org.apache.lucene.codecs.compressing.CompressingStoredFieldsFormat.fieldsWriter(CompressingStoredFieldsFormat.java:120)
	at org.apache.lucene.index.DefaultIndexingChain.initStoredFieldsWriter(DefaultIndexingChain.java:83)
	at org.apache.lucene.index.DefaultIndexingChain.startStoredFields(DefaultIndexingChain.java:270)
	at org.apache.lucene.index.DefaultIndexingChain.processDocument(DefaultIndexingChain.java:314)
	at org.apache.lucene.index.DocumentsWriterPerThread.updateDocuments(DocumentsWriterPerThread.java:282)
	at org.apache.lucene.index.DocumentsWriter.updateDocuments(DocumentsWriter.java:413)
	at org.apache.lucene.index.IndexWriter.updateDocuments(IndexWriter.java:1341)
	at com.github.rnewson.couchdb.lucene.DatabaseIndexer.handleResponse(DatabaseIndexer.java:370)
	at com.github.rnewson.couchdb.lucene.DatabaseIndexer.handleResponse(DatabaseIndexer.java:59)
	at org.apache.http.impl.client.AbstractHttpClient.execute(AbstractHttpClient.java:735)
	at org.apache.http.impl.client.AbstractHttpClient.execute(AbstractHttpClient.java:709)
	at org.apache.http.impl.client.AbstractHttpClient.execute(AbstractHttpClient.java:700)
	at com.github.rnewson.couchdb.lucene.DatabaseIndexer.run(DatabaseIndexer.java:450)
	at java.lang.Thread.run(Thread.java:745)
2015-09-30 18:35:38,723 DEBUG [recipes] NIOFSDirectory@/usr/local/couchdb-lucene-1.1.0-SNAPSHOT/indexes/967d3b56-f997-43bb-b283-36275aa279fa/6n7n7idfk8tpx4lj9u2fo7ell lockFactory=org.apache.lucene.store.SingleInstanceLockFactory@149e612 bumped since to 306
```

**Comment by rnewson** [comment]
oh! I guess I should always ask for the full log file, that would stick out quite nicely. Are you up and running now?

**Comment by larsimmisch** [comment]
Yes, I am, thank you. I just didn't close the ticket because I sort of hijacked an older one.

**Comment by rnewson** [comment]
:)

**Comment by dali15** [comment]
I still have the same problem for a week .... and there is no solution :(

**Comment by rnewson** [comment]
which problem? You are commenting on a very old ticket.

**Comment by dali15** [comment]
I installed couchdb-lucene but when I ask a query like this: http://localhost:5984/_fti/local/database/_design/foo/by_subject?q=hello
it gives me a database error not found

**Comment by rnewson** [comment]
This should be a new issue but I will answer here for expediency.

It is no longer possible, in CouchDB, to add new endpoints like _fti. You will need to provide your own proxy layer (HAProxy) if you wish to combine the couchdb and couchdb-lucene endpoints. You can talk to couchdb-lucene directly on its own port (5985).
