### ISSUE TITLE
CouchDB 2.0 support

### ISSUE THREAD

**Issue by psychowico** [rnewson/couchdb-lucene#235]
hi. I'm migrating my couchdb instance to 2.0 version and found some strange problem with lucene integration. It looks like lucene hangs on indexing process forever (until timeout error).

I have couchdb 2.0 instance on port `5984` and lucene on `5985`.

My lucene config file:
```ini
[lucene]
  ...
  timeout=10000
[local]
  url = http://roo:root@127.0.0.1:5984/
```

I'm skipping proxy for example clarity.

I send some request to lucene.
`curl -X GET "http://127.0.0.1:5985/local/ets/_design/lucene/activities?q=hello"`

As expected, couchdb got some connections from lucene 
couchdb-logs:
```
[notice] ... 127.0.0.1 root GET /ets/ 200 ok 91
[notice] ... 127.0.0.1 root GET /ets/_local%2Flucene 200 ok 1
[notice] ... 127.0.0.1 root GET /ets/ 200 ok 1
[notice] ... 127.0.0.1 root GET /ets/_all_docs?startkey=%22_design%22&endkey=%22_design0%22&include_docs=true 200 ok 19
```

Next Lucene start indexing (lucene logs):
`2016-09-30 09:21:00,157 INFO [ets] Indexing from update_seq start`

Then I get one more message from couchdb logs:
`[notice] ... 127.0.0.1 root GET /ets/_changes?limit=0&descending=true 200 ok 17`

Next I got no message in logs in next 10 seconds (when I changed `timeout` options to 60 seconds it was not messages in 60 seconds).

At the end Curl respond with simple `{"code":500}`.

Same config work without problems with couchdb 1.6.

Any advice?

**Comment by rnewson** [comment]
Hi, I could believe couchdb-lucene needs an update to be compatible with 2.0. I'll look into it.

**Comment by rnewson** [comment]
Hm, couchdb-lucene has had bigcouch support for a long long time, and it should be the same as what 2.0 needs.

**Comment by rnewson** [comment]
repro'ed. did you get this in the log too?

2016-09-30 13:39:47,760 WARN [ServletHandler] /local/db1/_design/lucene/foo
java.io.IOException: Search timed out.
	at com.github.rnewson.couchdb.lucene.DatabaseIndexer$IndexState.blockForLatest(DatabaseIndexer.java:171)
	at com.github.rnewson.couchdb.lucene.DatabaseIndexer$IndexState.borrowReader(DatabaseIndexer.java:87)
	at com.github.rnewson.couchdb.lucene.DatabaseIndexer$IndexState.borrowSearcher(DatabaseIndexer.java:107)
	at com.github.rnewson.couchdb.lucene.DatabaseIndexer.search(DatabaseIndexer.java:466)
	at com.github.rnewson.couchdb.lucene.LuceneServlet.doGetInternal(LuceneServlet.java:193)
	at com.github.rnewson.couchdb.lucene.LuceneServlet.doGet(LuceneServlet.java:171)
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:687)
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:790)
	at org.eclipse.jetty.servlet.ServletHolder.handle(ServletHolder.java:845)
	at org.eclipse.jetty.servlet.ServletHandler.doHandle(ServletHandler.java:583)
	at org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:143)
	at org.eclipse.jetty.server.handler.gzip.GzipHandler.handle(GzipHandler.java:459)
	at org.eclipse.jetty.server.handler.ContextHandler.doHandle(ContextHandler.java:1176)
	at org.eclipse.jetty.servlet.ServletHandler.doScope(ServletHandler.java:511)
	at org.eclipse.jetty.server.handler.ContextHandler.doScope(ContextHandler.java:1106)
	at org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:141)
	at org.eclipse.jetty.server.handler.HandlerWrapper.handle(HandlerWrapper.java:134)
	at org.eclipse.jetty.server.Server.handle(Server.java:524)
	at org.eclipse.jetty.server.HttpChannel.handle(HttpChannel.java:319)
	at org.eclipse.jetty.server.HttpConnection.onFillable(HttpConnection.java:253)
	at org.eclipse.jetty.io.AbstractConnection$ReadCallback.succeeded(AbstractConnection.java:273)
	at org.eclipse.jetty.io.FillInterest.fillable(FillInterest.java:95)
	at org.eclipse.jetty.io.SelectChannelEndPoint$2.run(SelectChannelEndPoint.java:93)
	at org.eclipse.jetty.util.thread.strategy.ExecuteProduceConsume.executeProduceConsume(ExecuteProduceConsume.java:303)
	at org.eclipse.jetty.util.thread.strategy.ExecuteProduceConsume.produceConsume(ExecuteProduceConsume.java:148)
	at org.eclipse.jetty.util.thread.strategy.ExecuteProduceConsume.run(ExecuteProduceConsume.java:136)
	at org.eclipse.jetty.util.thread.QueuedThreadPool.runJob(QueuedThreadPool.java:671)
	at org.eclipse.jetty.util.thread.QueuedThreadPool$2.run(QueuedThreadPool.java:589)
	at java.lang.Thread.run(Thread.java:745)

**Comment by psychowico** [comment]
no, for some reason I never get any WARN or ERR msg in `couchdb-lucene.log`/stdout.
but it looks like it can be this.

**Comment by rnewson** [comment]
fixed on master, would be great if you would confirm it.

**Comment by psychowico** [comment]
now I have problem with compilation. before I use version `1.0.2`.
now when I use `master` with java 1.8 and maven3 it hangs on downloading this:
`https://repo.maven.apache.org/maven2/net/java/jvnet-parent/3/jvnet-parent-3.pom`.
what setup do u use with master branch?

**Comment by rnewson** [comment]
java 1.8, maven 3.2.5. It builds from an empty ~/.m2/repository for me, perhaps you had a network issue at the time?

**Comment by mervynzhang** [comment]
We got the same issue, turns out that there are some data format changes in version 2, removing all old data, it works again.
